### ISSUE TITLE
[synapse deploy] Invalid return character or leading space in header during deployment

### ISSUE THREAD

**Issue by mikeleuer** [Azure-Samples/modern-data-warehouse-dataops#478]
## Description

Looks like there is an error when deploying deploy.sh
\e2e_samples\parking_sensors_synapse\scripts\deploy_synapse_artifacts.sh
(Pretty sure line 72)

## Expected Behavior

Successful Deployment 

## Reproduce

run bash deploy.sh

## Additional Context
```
Uploading Library Wheel Package to Workspace: ddo_transform-localdev-py2.py3-none-any.whl
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Invalid return character or leading space in header: Authorization
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 19, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 922, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 456, in prepare_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 317, in prepare
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 451, in prepare_headers
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/utils.py", line 978, in check_header_validity
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization
To open an issue, please run: 'az feedback'
The command failed with an unexpected error. Here is the traceback:
Invalid return character or leading space in header: Authorization
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 19, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 922, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 456, in prepare_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 317, in prepare
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 451, in prepare_headers
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/utils.py", line 978, in check_header_validity
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization
To open an issue, please run: 'az feedback'
```

Azure CLI

```
azure-cli                         2.32.0

core                              2.32.0
telemetry                          1.0.6

Extensions:
application-insights              0.1.14
azure-devops                      0.22.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mike.leuer\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

```

**Comment by devlace** [comment]
@mikeleuer Did you try using the devcontainer?

**Comment by mikeleuer** [comment]
I was able to fix it
